-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        args:
        - --django
    -   id: pretty-format-json
        args:
        - --autofix
        - --indent=2
    -   id: flake8
-   repo: local
    hooks:
    -   id: black
        name: Black - Code Style
        entry: pipenv run black
        args:
        - -q
        - --safe
        - --line-length=120
        language: system
        types: [python]
    -   id: isort
        name: Isort - Sort Imports
        entry: pipenv run isort
        language: system
        types: [python]
    -   id: pipenv-check
        name: Pipenv Check - Security Check
        entry: pipenv check
        language: system
        types: [python]
